stages:
- test

jobs:
- name: test:rspec
  stage: test
  image: manhbnt/ruby:2.7.1
  cache:
  - key: vendor_$CI_BRANCH
    paths:
    - vendor/bundle
  services:
  - image: mysql:5.7.22
    name: mysql_test
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: password_test
      MYSQL_ROOT_PASSWORD: password_test
  before_script:
  - cp database-ci.yml config/database.yml
  - bundle _2.1.4_ install --path vendor/bundle # _2.1.4_ if ruby 2.7.1 or 3.0.2
  - gem install rspec_junit_formatter
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate

  script:
  - DISABLE_SPRING=1 bundle _2.1.4_ exec rspec --format progress --format html --out ./.sun-ci-reports/rspec.html spec --format RspecJunitFormatter --out ~/sun-ci-reports/coverage/junit.xml
  artifacts:
    paths:
    - ./.sun-ci-reports/coverage/
    - ./.sun-ci-reports/rspec.html
    expires_in: 3 days
  test_result:
    type: junit
    path: ~/sun-ci-reports/coverage/junit.xml 
